config:
  runStrategy:
    runs: 1
scenarios:
- name: Test load-balancing on master nodes
  steps:
  - nodeAction:
      matches:
        - property:
            name: "az"
            value: "WEST.*"
      filters:
        - randomSample:
            size: 1
      actions:
        - stop:
            autoRestart: true
  - probeHTTP:
      target:
        url: "http://load-balancer.example.com"
